name: budget
version: 0.1.0.0
#synopsis:
#description:
homepage: https://github.com/githubuser/budget#readme
license: BSD-3-Clause
author: Author name here
maintainer: example@example.com
copyright: 2024 Author name here
category: Web
extra-source-files:
  - README.md
  - CHANGELOG.md

language: GHC2021

default-extensions:
  - OverloadedStrings
  - BlockArguments
  - OverloadedRecordDot

dependencies:
  - base >= 4.7 && < 5
  - sqlite-simple
  - lucid2
  - scotty
  - password
  - time
  - dotenv
  - aeson
  - smtp-mail
  - text
  - wai-middleware-static
  - raw-strings-qq
  - envy
  - mtl
  - transformers
  - lens
  - wai-extra
  - monad-logger
  - uuid
  - MonadRandom
  - unliftio-core
  - mime-mail
  - uri-encode
  - format-numbers
  - data-default

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

executables:
  budget:
    source-dirs: src
    main: Main.hs
