name: budget
version: 0.1.0.0
#synopsis:
#description:
homepage: https://github.com/githubuser/budget#readme
license: BSD-3-Clause
author: Author name here
maintainer: example@example.com
copyright: 2024 Author name here
category: Web
extra-source-files:
  - README.md
  - CHANGELOG.md

language: GHC2021

default-extensions:
  - OverloadedStrings
  - BlockArguments
  - OverloadedRecordDot
  - LambdaCase
  - GADTs
  - TypeFamilies
  - DataKinds

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - containers
  - data-default
  - dotenv
  - effectful
  - effectful-core
  - effectful-th
  - envy
  - exceptions
  - format-numbers
  - http-types
  - lens
  - lucid2
  - mime-mail
  - monad-logger
  - MonadRandom
  - mtl
  - password
  - raw-strings-qq
  - scotty
  - smtp-mail
  - sqlite-simple
  - text
  - time
  - transformers
  - unliftio-core
  - uri-encode
  - uuid
  - wai
  - wai-extra
  - wai-middleware-static

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

executables:
  budget:
    source-dirs: src
    main: Main.hs
