on: [push]
name: build
jobs:
  runhaskell:
    name: budget
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-version: "latest"
      - run: stack install --local-bin-path /home/runner/work/budget/budget/exe
      - run: ls /home/runner/work/budget/budget/exe
